version: '2'

services:
  mongo:
    image: mongo:3.6.6
    container_name: recipe-mongodb
    volumes:
      - ./docker/data/mongo:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: recipe
    depends_on:
     - mongo
    environment:
     - MONGODB_URL=mongodb://mongo/recipe